# Generated by Django 3.0.6 on 2020-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20200525_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(max_length=6),
        ),
    ]
