# Generated by Django 3.0.6 on 2020-05-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_auto_20200525_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('complete', 'complete')], max_length=20),
        ),
    ]
