# Generated by Django 3.0.6 on 2020-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_auto_20200525_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='logger.Author'),
        ),
    ]
