# Generated by Django 3.0.6 on 2020-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_auto_20200525_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='logger.Author'),
        ),
    ]
