# Generated by Django 3.0.6 on 2020-05-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_auto_20200525_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
