# Generated by Django 3.0.6 on 2020-05-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_auto_20200526_0506'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(status='paid'), fields=['total'], name='total_idx'),
        ),
    ]
