# Generated by Django 3.0.6 on 2020-05-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_auto_20200530_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_index=True, max_length=4),
        ),
    ]
